=== dderevjanik/battle-city-reforged/data/map.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "map.schema.json",
  "type": "object",
  "required": ["width", "height", "spawn"],
  "additionalProperties": false,
  "properties": {
    "version": {
      "type": "number",
      "default": 1
    },
    "tileset": {
      "type": "string",
      "enum": ["classic", "modern"],
      "default": "classic"
    },
    "width": {
      "type": "integer",
      "minimum": 1
    },
    "height": {
      "type": "integer",
      "minimum": 1
    },
    "spawn": {
      "type": "object",
      "required": ["enemy", "player"],
      "additionalProperties": false,
      "properties": {
        "enemy": {
          "type": "object",
          "required": ["spawnDelay", "maxAliveCount", "locations"],
          "additionalProperties": false,
          "properties": {
            "spawnDelay": { "type": "number" },
            "maxAliveCount": { "type": "integer", "minimum": 1 },
            "locations": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "object",
                "required": ["x", "y"],
                "additionalProperties": false,
                "properties": {
                  "x": { "type": "number" },
                  "y": { "type": "number" }
                }
              }
            },
            "list": {
              "type": "array",
              "default": [],
              "items": {
                "type": "object",
                "required": ["type"],
                "additionalProperties": false,
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": ["basic", "fast", "fast_armored", "medium", "heavy"]
                  },
                  "ai": {
                    "type": "string",
                    "enum": ["classic", "hunter", "ambush", "attack_base"]
                  },
                  "drop": {
                    "oneOf": [
                      {
                        "type": "string",
                        "enum": ["random", "defence", "freeze", "life", "shield", "upgrade", "wipeout"]
                      },
                      {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                          "type": "string",
                          "enum": ["random", "defence", "freeze", "life", "shield", "upgrade", "wipeout"]
                        }
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "player": {
          "type": "object",
          "required": ["locations"],
          "additionalProperties": false,
          "properties": {
            "locations": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "object",
                "required": ["x", "y"],
                "additionalProperties": false,
                "properties": {
                  "x": { "type": "number" },
                  "y": { "type": "number" }
                }
              }
            }
          }
        },
        "base": {
          "type": "object",
          "required": ["x", "y"],
          "additionalProperties": false,
          "properties": {
            "x": { "type": "number" },
            "y": { "type": "number" }
          }
        },
        "bases": {
          "type": "array",
          "items": {
            "type": "object",
            "required": ["x", "y"],
            "additionalProperties": false,
            "properties": {
              "x": { "type": "number" },
              "y": { "type": "number" }
            }
          }
        }
      }
    },
    "terrain": {
      "type": "object",
      "additionalProperties": false,
      "default": {},
      "properties": {
        "regions": {
          "type": "array",
          "default": [],
          "items": {
            "type": "object",
            "required": ["type", "x", "y", "width", "height"],
            "additionalProperties": false,
            "properties": {
              "type": {
                "type": "string",
                "enum": ["brick", "brick-super", "steel", "jungle", "water", "ice", "menu-brick", "inverse-brick", "blue-brick"]
              },
              "x": { "type": "number" },
              "y": { "type": "number" },
              "width": { "type": "number" },
              "height": { "type": "number" }
            }
          }
        }
      }
    }
  }
}

=== dderevjanik/battle-city-reforged/data/maps/original/23.json
{
  "version": 1,
  "tileset": "classic",
  "width": 832,
  "height": 832,
  "spawn": {
    "enemy": {
      "spawnDelay": 3,
      "maxAliveCount": 4,
      "list": [
        {
          "ai": "classic",
          "type": "heavy"
        },
        {
          "ai": "classic",
          "type": "heavy"
        },
        {
          "ai": "classic",
          "type": "heavy"
        },
        {
          "drop": "random",
          "ai": "classic",
          "type": "heavy"
        },
        {
          "ai": "classic",
          "type": "heavy"
        },
        {
          "ai": "classic",
          "type": "heavy"
        },
        {
          "ai": "classic",
          "type": "medium"
        },
        {
          "ai": "classic",
          "type": "medium"
        },
        {
          "ai": "classic",
          "type": "medium"
        },
        {
          "ai": "classic",
          "type": "medium"
        },
        {
          "drop": "random",
          "ai": "classic",
          "type": "fast"
        },
        {
          "ai": "classic",
          "type": "fast"
        },
        {
          "ai": "classic",
          "type": "fast"
        },
        {
          "ai": "classic",
          "type": "fast"
        },
        {
          "ai": "classic",
          "type": "fast"
        },
        {
          "ai": "classic",
          "type": "fast"
        },
        {
          "ai": "classic",
          "type": "fast"
        },
        {
          "drop": "random",
          "ai": "classic",
          "type": "fast"
        },
        {
          "ai": "classic",
          "type": "fast"
        },
        {
          "ai": "classic",
          "type": "fast"
        }
      ],
      "locations": [
        {
          "x": 384,
          "y": 0
        },
        {
          "x": 768,
          "y": 0
        },
        {
          "x": 0,
          "y": 0
        }
      ]
    },
    "player": {
      "locations": [
        {
          "x": 256,
          "y": 768
        },
        {
          "x": 512,
          "y": 768
        }
      ]
    }
  },
  "terrain": {
    "regions": [
      {
        "type": "steel",
        "x": 384,
        "y": 64,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 384,
        "y": 128,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 320,
        "y": 64,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 384,
        "y": 192,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 384,
        "y": 256,
        "width": 64,
        "height": 64
      },
      {
        "type": "brick",
        "x": 448,
        "y": 192,
        "width": 64,
        "height": 64
      },
      {
        "type": "brick",
        "x": 320,
        "y": 192,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 640,
        "y": 192,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 704,
        "y": 192,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 576,
        "y": 192,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 512,
        "y": 192,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 512,
        "y": 256,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 448,
        "y": 256,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 448,
        "y": 320,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 384,
        "y": 320,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 320,
        "y": 320,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 320,
        "y": 256,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 256,
        "y": 256,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 256,
        "y": 192,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 192,
        "y": 192,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 320,
        "y": 384,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 384,
        "y": 384,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 448,
        "y": 384,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 384,
        "y": 448,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 576,
        "y": 256,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 512,
        "y": 320,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 256,
        "y": 320,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 192,
        "y": 256,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 128,
        "y": 192,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 64,
        "y": 192,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 320,
        "y": 448,
        "width": 32,
        "height": 32
      },
      {
        "type": "steel",
        "x": 352,
        "y": 448,
        "width": 32,
        "height": 32
      },
      {
        "type": "steel",
        "x": 448,
        "y": 448,
        "width": 32,
        "height": 32
      },
      {
        "type": "steel",
        "x": 480,
        "y": 448,
        "width": 32,
        "height": 32
      },
      {
        "type": "steel",
        "x": 512,
        "y": 512,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 576,
        "y": 576,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 384,
        "y": 576,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 192,
        "y": 576,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 256,
        "y": 512,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 256,
        "y": 480,
        "width": 32,
        "height": 32
      },
      {
        "type": "steel",
        "x": 288,
        "y": 480,
        "width": 32,
        "height": 32
      },
      {
        "type": "steel",
        "x": 512,
        "y": 480,
        "width": 32,
        "height": 32
      },
      {
        "type": "steel",
        "x": 544,
        "y": 480,
        "width": 32,
        "height": 32
      },
      {
        "type": "steel",
        "x": 384,
        "y": 544,
        "width": 32,
        "height": 32
      },
      {
        "type": "steel",
        "x": 416,
        "y": 544,
        "width": 32,
        "height": 32
      },
      {
        "type": "steel",
        "x": 0,
        "y": 384,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 768,
        "y": 384,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 768,
        "y": 448,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 768,
        "y": 320,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 704,
        "y": 384,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 64,
        "y": 384,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 0,
        "y": 320,
        "width": 64,
        "height": 64
      },
      {
        "type": "jungle",
        "x": 0,
        "y": 448,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 128,
        "y": 768,
        "width": 64,
        "height": 64
      },
      {
        "type": "steel",
        "x": 640,
        "y": 768,
        "width": 64,
        "height": 64
      },
      {
        "type": "brick",
        "x": 352,
        "y": 736,
        "width": 128,
        "height": 32
      },
      {
        "type": "brick",
        "x": 352,
        "y": 768,
        "width": 32,
        "height": 64
      },
      {
        "type": "brick",
        "x": 448,
        "y": 768,
        "width": 32,
        "height": 64
      }
    ]
  }
}
